### ISSUE TITLE
TSR-1-2450 clearance

### ISSUE THREAD

**Issue by FLHerne** [Simulators/simulator-type2#1]
While building an interface board using the TSR regulator that's suggested as an alternative, I've found that the physical clearance against capacitor C1 is very tight.

It can only be installed with the pins up against the far edge of the PCB holes, and even then one corner touches the capacitor.

While this should work, it's not ideal.

**Comment by Simulators** [comment]
Hello, which revision of the PCB, please?

**Comment by FLHerne** [comment]
Rev. C, 09/2018

**Comment by Simulators** [comment]
Agreed, error introduced in Rev C. Workaround #1, if your deployment permits, use a conventional voltage regulator, perhaps with a small heatsink. That should be adequate for almost all deployments except for high current demands e.g. where there are large numbers of optical sensors. Workaround #2, contact me via the website form and I can send you a surplus Rev A board, which has better clearance. Permanent fix will follow in an updated board design.

**Comment by FLHerne** [comment]
Thanks for the quick response.

It does just barely fit, and since neither component body is conductive I don't think that them touching will cause a functional problem; it just looks rather inelegant...

I do now have the board powered on and programmed, it seems to be working fine.

Should I need further interface boards beyond the pair I already have parts for, I shall probably use a conventional regulator.
